spring.application.name=voting-system

# Render port
server.port=${PORT:8080}

# MySQL - Aiven (with local fallback if environment variables are not set)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:voting_db;DB_CLOSE_DELAY=-1;MODE=MySQL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.devtools.restart.exclude=**/*.csv,static/**,public/**,templates/**
